import os, sys
import datetime as dt
import pandas as pd

xlsx = pd.read_excel("wecc240/Bus GIS.xlsx",usecols=[0,11,12],dtype=float)

print(f"// generated by {sys.argv} on {dt.datetime.now}")
for row,data in xlsx.iterrows():
    print(f"modify wecc240_psse_N_{data[0]:.0f}.latitude {data[1]};")
    print(f"modify wecc240_psse_N_{data[0]:.0f}.longitude {data[2]};")
