name: Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop
    
    steps:
    - uses: actions/checkout@v4

    - name: Run simulation
      run: |
        cd model
        gridlabd wecc240.glm
      
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: model/
