name: validate

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  check-gridlabd:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop

    steps:
    - uses: actions/checkout@v4

    - name: Test GridLAB-D model
      run: |
        cd model
        gridlabd wecc240.glm

    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: model/
      
  check-pypower:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop

    steps:
    - uses: actions/checkout@v4

    - name: Test pypower model
      run: |
        cd model
        gridlabd python raw2py.py
      
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: model/
