name: Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop
    
    steps:
    - uses: actions/checkout@v4

    - name: Run simulation
      run: |
        cd model
        gridlabd wecc240.glm
      
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: model/

  pypower:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
    
    - name: Install requirements
      run: |
        cd pypower
        python3 -m pip install --upgrade pip -r requirements.txt

    - name: Analyse code
      run: |
        cd pypower
        pylint *.py
