name: PyPOWER

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  pypower:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install packages
      run: |
        cd pypower
        python3 -m pip install --upgrade pip -r requirements.txt pylint

    - name: Analyse code
      run: |
        cd pypower
        make pylint

    - name: Run tests
      run: |
        cd pypower
        make tests || ( tar cfz ../pypower-tests.tarz tests ; false )
        tar cfz ../pypower-tests.tarz tests

    - name: Update summaries
      run: |
        cd pypower
        make summaries
        tar cfz ../pypower-summaries.tarz summaries

    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: pypower-tests
        path: pypower-tests.tarz

    - name: Save summary output
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: pypower-summaries
        path: pypower-summaries.tarz
