name: Quicksim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Run simulation
      run: |
        python3 -m pip install pip --upgrade -r requirements.txt
        cd model
        python3 quick_sim.py
      
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: model/
